# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

###############################################################################
# Boiler-plate

# cross-platform directory manipulation
ifeq ($(shell echo $$OS),$$OS)
    MAKEDIR = if not exist "$(1)" mkdir "$(1)"
    RM = rmdir /S /Q "$(1)"
else
    MAKEDIR = '$(SHELL)' -c "mkdir -p \"$(1)\""
    RM = '$(SHELL)' -c "rm -rf \"$(1)\""
endif

OBJDIR := BUILD
# Move to the build directory
ifeq (,$(filter $(OBJDIR),$(notdir $(CURDIR))))
.SUFFIXES:
mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
MAKETARGET = '$(MAKE)' --no-print-directory -C $(OBJDIR) -f '$(mkfile_path)' \
		'SRCDIR=$(CURDIR)' $(MAKECMDGOALS)
.PHONY: $(OBJDIR) clean
all:
	+@$(call MAKEDIR,$(OBJDIR))
	+@$(MAKETARGET)
$(OBJDIR): all
Makefile : ;
% :: $(OBJDIR) ; :
clean :
	$(call RM,$(OBJDIR))

else

# trick rules into thinking we are in the root, when we are in the bulid dir
VPATH = ..

# Boiler-plate
###############################################################################
# Project settings

PROJECT := ACD52832_Beacon_basic_example


# Project settings
###############################################################################
# Objects and Paths

OBJECTS += ./source/ble_process/BLEProcess.o
OBJECTS += ./source/measurement/MeasurementProcess.o
OBJECTS += ./sd/sdcardProcess.o
OBJECTS += ./source/ble_server/EnviromentSensingServer.o
OBJECTS += ./source/main.o
OBJECTS += ./mbed-os/drivers/AnalogIn.o
OBJECTS += ./mbed-os/drivers/BusIn.o
OBJECTS += ./mbed-os/drivers/BusInOut.o
OBJECTS += ./mbed-os/drivers/BusOut.o
OBJECTS += ./mbed-os/drivers/CAN.o
OBJECTS += ./mbed-os/drivers/Ethernet.o
OBJECTS += ./mbed-os/drivers/FlashIAP.o
OBJECTS += ./mbed-os/drivers/I2C.o
OBJECTS += ./mbed-os/drivers/I2CSlave.o
OBJECTS += ./mbed-os/drivers/InterruptIn.o
OBJECTS += ./mbed-os/drivers/InterruptManager.o
OBJECTS += ./mbed-os/drivers/MbedCRC.o
OBJECTS += ./mbed-os/drivers/RawSerial.o
OBJECTS += ./mbed-os/drivers/SPI.o
OBJECTS += ./mbed-os/drivers/SPISlave.o
OBJECTS += ./mbed-os/drivers/Serial.o
OBJECTS += ./mbed-os/drivers/SerialBase.o
OBJECTS += ./mbed-os/drivers/TableCRC.o
OBJECTS += ./mbed-os/drivers/Ticker.o
OBJECTS += ./mbed-os/drivers/Timeout.o
OBJECTS += ./mbed-os/drivers/Timer.o
OBJECTS += ./mbed-os/drivers/TimerEvent.o
OBJECTS += ./mbed-os/drivers/UARTSerial.o
OBJECTS += ./mbed-os/events/EventQueue.o
OBJECTS += ./mbed-os/events/equeue/equeue.o
OBJECTS += ./mbed-os/events/equeue/equeue_mbed.o
OBJECTS += ./mbed-os/events/equeue/equeue_posix.o
OBJECTS += ./mbed-os/events/mbed_shared_queues.o
OBJECTS += ./mbed-os/features/FEATURE_BLE/source/BLE.o
OBJECTS += ./mbed-os/features/FEATURE_BLE/source/BLEInstanceBase.o
OBJECTS += ./mbed-os/features/FEATURE_BLE/source/DiscoveredCharacteristic.o
OBJECTS += ./mbed-os/features/FEATURE_BLE/source/GapScanningParams.o
OBJECTS += ./mbed-os/features/FEATURE_BLE/source/generic/GenericGap.o
OBJECTS += ./mbed-os/features/FEATURE_BLE/source/generic/GenericGattClient.o
OBJECTS += ./mbed-os/features/FEATURE_BLE/source/generic/GenericSecurityManager.o
OBJECTS += ./mbed-os/features/FEATURE_BLE/source/services/DFUService.o
OBJECTS += ./mbed-os/features/FEATURE_BLE/source/services/UARTService.o
OBJECTS += ./mbed-os/features/FEATURE_BLE/source/services/URIBeaconConfigService.o
OBJECTS += ./mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/btle.o
OBJECTS += ./mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/btle_gap.o
OBJECTS += ./mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/btle_security.o
OBJECTS += ./mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/btle_security_pm.o
OBJECTS += ./mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/custom/custom_helper.o
OBJECTS += ./mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/nRF5XPalGattClient.o
OBJECTS += ./mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/nRF5xGap.o
OBJECTS += ./mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/nRF5xGattServer.o
OBJECTS += ./mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/nRF5xn.o
OBJECTS += ./mbed-os/features/cellular/easy_cellular/CellularConnectionFSM.o
OBJECTS += ./mbed-os/features/cellular/easy_cellular/EasyCellularConnection.o
OBJECTS += ./mbed-os/features/cellular/framework/AT/ATHandler.o
OBJECTS += ./mbed-os/features/cellular/framework/AT/AT_CellularBase.o
OBJECTS += ./mbed-os/features/cellular/framework/AT/AT_CellularDevice.o
OBJECTS += ./mbed-os/features/cellular/framework/AT/AT_CellularInformation.o
OBJECTS += ./mbed-os/features/cellular/framework/AT/AT_CellularNetwork.o
OBJECTS += ./mbed-os/features/cellular/framework/AT/AT_CellularPower.o
OBJECTS += ./mbed-os/features/cellular/framework/AT/AT_CellularSIM.o
OBJECTS += ./mbed-os/features/cellular/framework/AT/AT_CellularSMS.o
OBJECTS += ./mbed-os/features/cellular/framework/AT/AT_CellularStack.o
OBJECTS += ./mbed-os/features/cellular/framework/common/CellularUtil.o
OBJECTS += ./mbed-os/features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.o
OBJECTS += ./mbed-os/features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularNetwork.o
OBJECTS += ./mbed-os/features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularPower.o
OBJECTS += ./mbed-os/features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularSIM.o
OBJECTS += ./mbed-os/features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.o
OBJECTS += ./mbed-os/features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.o
OBJECTS += ./mbed-os/features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularNetwork.o
OBJECTS += ./mbed-os/features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.o
OBJECTS += ./mbed-os/features/cellular/framework/targets/TELIT/HE910/TELIT_HE910.o
OBJECTS += ./mbed-os/features/cellular/framework/targets/TELIT/HE910/TELIT_HE910_CellularNetwork.o
OBJECTS += ./mbed-os/features/cellular/framework/targets/TELIT/HE910/TELIT_HE910_CellularPower.o
OBJECTS += ./mbed-os/features/cellular/framework/targets/UBLOX/LISA_U/UBLOX_LISA_U.o
OBJECTS += ./mbed-os/features/cellular/framework/targets/UBLOX/LISA_U/UBLOX_LISA_U_CellularNetwork.o
OBJECTS += ./mbed-os/features/cellular/framework/targets/UBLOX/LISA_U/UBLOX_LISA_U_CellularPower.o
OBJECTS += ./mbed-os/features/filesystem/Dir.o
OBJECTS += ./mbed-os/features/filesystem/File.o
OBJECTS += ./mbed-os/features/filesystem/FileSystem.o
OBJECTS += ./mbed-os/features/filesystem/bd/ChainingBlockDevice.o
OBJECTS += ./mbed-os/features/filesystem/bd/ExhaustibleBlockDevice.o
OBJECTS += ./mbed-os/features/filesystem/bd/HeapBlockDevice.o
OBJECTS += ./mbed-os/features/filesystem/bd/MBRBlockDevice.o
OBJECTS += ./mbed-os/features/filesystem/bd/ObservingBlockDevice.o
OBJECTS += ./mbed-os/features/filesystem/bd/ProfilingBlockDevice.o
OBJECTS += ./mbed-os/features/filesystem/bd/ReadOnlyBlockDevice.o
OBJECTS += ./mbed-os/features/filesystem/bd/SlicingBlockDevice.o
OBJECTS += ./mbed-os/features/filesystem/fat/ChaN/ff.o
OBJECTS += ./mbed-os/features/filesystem/fat/ChaN/ffunicode.o
OBJECTS += ./mbed-os/features/filesystem/fat/FATFileSystem.o
OBJECTS += ./mbed-os/features/filesystem/littlefs/LittleFileSystem.o
OBJECTS += ./mbed-os/features/filesystem/littlefs/littlefs/lfs.o
OBJECTS += ./mbed-os/features/filesystem/littlefs/littlefs/lfs_util.o
OBJECTS += ./mbed-os/features/frameworks/greentea-client/source/greentea_metrics.o
OBJECTS += ./mbed-os/features/frameworks/greentea-client/source/greentea_serial.o
OBJECTS += ./mbed-os/features/frameworks/greentea-client/source/greentea_test_env.o
OBJECTS += ./mbed-os/features/frameworks/unity/source/unity.o
OBJECTS += ./mbed-os/features/frameworks/utest/mbed-utest-shim.o
OBJECTS += ./mbed-os/features/frameworks/utest/source/unity_handler.o
OBJECTS += ./mbed-os/features/frameworks/utest/source/utest_case.o
OBJECTS += ./mbed-os/features/frameworks/utest/source/utest_default_handlers.o
OBJECTS += ./mbed-os/features/frameworks/utest/source/utest_greentea_handlers.o
OBJECTS += ./mbed-os/features/frameworks/utest/source/utest_harness.o
OBJECTS += ./mbed-os/features/frameworks/utest/source/utest_shim.o
OBJECTS += ./mbed-os/features/frameworks/utest/source/utest_stack_trace.o
OBJECTS += ./mbed-os/features/frameworks/utest/source/utest_types.o
OBJECTS += ./mbed-os/features/lorawan/LoRaWANInterface.o
OBJECTS += ./mbed-os/features/lorawan/LoRaWANStack.o
OBJECTS += ./mbed-os/features/lorawan/lorastack/mac/LoRaMac.o
OBJECTS += ./mbed-os/features/lorawan/lorastack/mac/LoRaMacChannelPlan.o
OBJECTS += ./mbed-os/features/lorawan/lorastack/mac/LoRaMacCommand.o
OBJECTS += ./mbed-os/features/lorawan/lorastack/mac/LoRaMacCrypto.o
OBJECTS += ./mbed-os/features/lorawan/lorastack/mac/LoRaMacMcps.o
OBJECTS += ./mbed-os/features/lorawan/lorastack/mac/LoRaMacMib.o
OBJECTS += ./mbed-os/features/lorawan/lorastack/mac/LoRaMacMlme.o
OBJECTS += ./mbed-os/features/lorawan/lorastack/phy/LoRaPHY.o
OBJECTS += ./mbed-os/features/lorawan/lorastack/phy/LoRaPHYAS923.o
OBJECTS += ./mbed-os/features/lorawan/lorastack/phy/LoRaPHYAU915.o
OBJECTS += ./mbed-os/features/lorawan/lorastack/phy/LoRaPHYCN470.o
OBJECTS += ./mbed-os/features/lorawan/lorastack/phy/LoRaPHYCN779.o
OBJECTS += ./mbed-os/features/lorawan/lorastack/phy/LoRaPHYEU433.o
OBJECTS += ./mbed-os/features/lorawan/lorastack/phy/LoRaPHYEU868.o
OBJECTS += ./mbed-os/features/lorawan/lorastack/phy/LoRaPHYIN865.o
OBJECTS += ./mbed-os/features/lorawan/lorastack/phy/LoRaPHYKR920.o
OBJECTS += ./mbed-os/features/lorawan/lorastack/phy/LoRaPHYUS915.o
OBJECTS += ./mbed-os/features/lorawan/lorastack/phy/LoRaPHYUS915Hybrid.o
OBJECTS += ./mbed-os/features/lorawan/system/LoRaWANTimer.o
OBJECTS += ./mbed-os/features/mbedtls/platform/src/mbed_trng.o
OBJECTS += ./mbed-os/features/mbedtls/src/aes.o
OBJECTS += ./mbed-os/features/mbedtls/src/aesni.o
OBJECTS += ./mbed-os/features/mbedtls/src/arc4.o
OBJECTS += ./mbed-os/features/mbedtls/src/asn1parse.o
OBJECTS += ./mbed-os/features/mbedtls/src/asn1write.o
OBJECTS += ./mbed-os/features/mbedtls/src/base64.o
OBJECTS += ./mbed-os/features/mbedtls/src/bignum.o
OBJECTS += ./mbed-os/features/mbedtls/src/blowfish.o
OBJECTS += ./mbed-os/features/mbedtls/src/camellia.o
OBJECTS += ./mbed-os/features/mbedtls/src/ccm.o
OBJECTS += ./mbed-os/features/mbedtls/src/certs.o
OBJECTS += ./mbed-os/features/mbedtls/src/cipher.o
OBJECTS += ./mbed-os/features/mbedtls/src/cipher_wrap.o
OBJECTS += ./mbed-os/features/mbedtls/src/cmac.o
OBJECTS += ./mbed-os/features/mbedtls/src/ctr_drbg.o
OBJECTS += ./mbed-os/features/mbedtls/src/debug.o
OBJECTS += ./mbed-os/features/mbedtls/src/des.o
OBJECTS += ./mbed-os/features/mbedtls/src/dhm.o
OBJECTS += ./mbed-os/features/mbedtls/src/ecdh.o
OBJECTS += ./mbed-os/features/mbedtls/src/ecdsa.o
OBJECTS += ./mbed-os/features/mbedtls/src/ecjpake.o
OBJECTS += ./mbed-os/features/mbedtls/src/ecp.o
OBJECTS += ./mbed-os/features/mbedtls/src/ecp_curves.o
OBJECTS += ./mbed-os/features/mbedtls/src/entropy.o
OBJECTS += ./mbed-os/features/mbedtls/src/entropy_poll.o
OBJECTS += ./mbed-os/features/mbedtls/src/error.o
OBJECTS += ./mbed-os/features/mbedtls/src/gcm.o
OBJECTS += ./mbed-os/features/mbedtls/src/havege.o
OBJECTS += ./mbed-os/features/mbedtls/src/hmac_drbg.o
OBJECTS += ./mbed-os/features/mbedtls/src/md.o
OBJECTS += ./mbed-os/features/mbedtls/src/md2.o
OBJECTS += ./mbed-os/features/mbedtls/src/md4.o
OBJECTS += ./mbed-os/features/mbedtls/src/md5.o
OBJECTS += ./mbed-os/features/mbedtls/src/md_wrap.o
OBJECTS += ./mbed-os/features/mbedtls/src/memory_buffer_alloc.o
OBJECTS += ./mbed-os/features/mbedtls/src/net_sockets.o
OBJECTS += ./mbed-os/features/mbedtls/src/oid.o
OBJECTS += ./mbed-os/features/mbedtls/src/padlock.o
OBJECTS += ./mbed-os/features/mbedtls/src/pem.o
OBJECTS += ./mbed-os/features/mbedtls/src/pk.o
OBJECTS += ./mbed-os/features/mbedtls/src/pk_wrap.o
OBJECTS += ./mbed-os/features/mbedtls/src/pkcs11.o
OBJECTS += ./mbed-os/features/mbedtls/src/pkcs12.o
OBJECTS += ./mbed-os/features/mbedtls/src/pkcs5.o
OBJECTS += ./mbed-os/features/mbedtls/src/pkparse.o
OBJECTS += ./mbed-os/features/mbedtls/src/pkwrite.o
OBJECTS += ./mbed-os/features/mbedtls/src/platform.o
OBJECTS += ./mbed-os/features/mbedtls/src/ripemd160.o
OBJECTS += ./mbed-os/features/mbedtls/src/rsa.o
OBJECTS += ./mbed-os/features/mbedtls/src/rsa_internal.o
OBJECTS += ./mbed-os/features/mbedtls/src/sha1.o
OBJECTS += ./mbed-os/features/mbedtls/src/sha256.o
OBJECTS += ./mbed-os/features/mbedtls/src/sha512.o
OBJECTS += ./mbed-os/features/mbedtls/src/ssl_cache.o
OBJECTS += ./mbed-os/features/mbedtls/src/ssl_ciphersuites.o
OBJECTS += ./mbed-os/features/mbedtls/src/ssl_cli.o
OBJECTS += ./mbed-os/features/mbedtls/src/ssl_cookie.o
OBJECTS += ./mbed-os/features/mbedtls/src/ssl_srv.o
OBJECTS += ./mbed-os/features/mbedtls/src/ssl_ticket.o
OBJECTS += ./mbed-os/features/mbedtls/src/ssl_tls.o
OBJECTS += ./mbed-os/features/mbedtls/src/threading.o
OBJECTS += ./mbed-os/features/mbedtls/src/timing.o
OBJECTS += ./mbed-os/features/mbedtls/src/version.o
OBJECTS += ./mbed-os/features/mbedtls/src/version_features.o
OBJECTS += ./mbed-os/features/mbedtls/src/x509.o
OBJECTS += ./mbed-os/features/mbedtls/src/x509_create.o
OBJECTS += ./mbed-os/features/mbedtls/src/x509_crl.o
OBJECTS += ./mbed-os/features/mbedtls/src/x509_crt.o
OBJECTS += ./mbed-os/features/mbedtls/src/x509_csr.o
OBJECTS += ./mbed-os/features/mbedtls/src/x509write_crt.o
OBJECTS += ./mbed-os/features/mbedtls/src/x509write_csr.o
OBJECTS += ./mbed-os/features/mbedtls/src/xtea.o
OBJECTS += ./mbed-os/features/mbedtls/targets/hash_wrappers.o
OBJECTS += ./mbed-os/features/netsocket/NetworkInterface.o
OBJECTS += ./mbed-os/features/netsocket/NetworkStack.o
OBJECTS += ./mbed-os/features/netsocket/Socket.o
OBJECTS += ./mbed-os/features/netsocket/SocketAddress.o
OBJECTS += ./mbed-os/features/netsocket/TCPServer.o
OBJECTS += ./mbed-os/features/netsocket/TCPSocket.o
OBJECTS += ./mbed-os/features/netsocket/UDPSocket.o
OBJECTS += ./mbed-os/features/netsocket/WiFiAccessPoint.o
OBJECTS += ./mbed-os/features/netsocket/cellular/generic_modem_driver/OnboardCellularInterface.o
OBJECTS += ./mbed-os/features/netsocket/cellular/generic_modem_driver/PPPCellularInterface.o
OBJECTS += ./mbed-os/features/netsocket/cellular/generic_modem_driver/UARTCellularInterface.o
OBJECTS += ./mbed-os/features/netsocket/nsapi_dns.o
OBJECTS += ./mbed-os/features/nvstore/source/nvstore.o
OBJECTS += ./mbed-os/hal/mbed_critical_section_api.o
OBJECTS += ./mbed-os/hal/mbed_flash_api.o
OBJECTS += ./mbed-os/hal/mbed_gpio.o
OBJECTS += ./mbed-os/hal/mbed_itm_api.o
OBJECTS += ./mbed-os/hal/mbed_lp_ticker_api.o
OBJECTS += ./mbed-os/hal/mbed_pinmap_common.o
OBJECTS += ./mbed-os/hal/mbed_sleep_manager.o
OBJECTS += ./mbed-os/hal/mbed_ticker_api.o
OBJECTS += ./mbed-os/hal/mbed_us_ticker_api.o
OBJECTS += ./mbed-os/platform/ATCmdParser.o
OBJECTS += ./mbed-os/platform/CallChain.o
OBJECTS += ./mbed-os/platform/FileBase.o
OBJECTS += ./mbed-os/platform/FileHandle.o
OBJECTS += ./mbed-os/platform/FilePath.o
OBJECTS += ./mbed-os/platform/FileSystemHandle.o
OBJECTS += ./mbed-os/platform/LocalFileSystem.o
OBJECTS += ./mbed-os/platform/Stream.o
OBJECTS += ./mbed-os/platform/mbed_alloc_wrappers.o
OBJECTS += ./mbed-os/platform/mbed_application.o
OBJECTS += ./mbed-os/platform/mbed_assert.o
OBJECTS += ./mbed-os/platform/mbed_board.o
OBJECTS += ./mbed-os/platform/mbed_critical.o
OBJECTS += ./mbed-os/platform/mbed_error.o
OBJECTS += ./mbed-os/platform/mbed_interface.o
OBJECTS += ./mbed-os/platform/mbed_mem_trace.o
OBJECTS += ./mbed-os/platform/mbed_mktime.o
OBJECTS += ./mbed-os/platform/mbed_poll.o
OBJECTS += ./mbed-os/platform/mbed_retarget.o
OBJECTS += ./mbed-os/platform/mbed_rtc_time.o
OBJECTS += ./mbed-os/platform/mbed_sdk_boot.o
OBJECTS += ./mbed-os/platform/mbed_semihost_api.o
OBJECTS += ./mbed-os/platform/mbed_stats.o
OBJECTS += ./mbed-os/platform/mbed_wait_api_no_rtos.o
OBJECTS += ./mbed-os/platform/mbed_wait_api_rtos.o
OBJECTS += ./mbed-os/rtos/ConditionVariable.o
OBJECTS += ./mbed-os/rtos/EventFlags.o
OBJECTS += ./mbed-os/rtos/Kernel.o
OBJECTS += ./mbed-os/rtos/Mutex.o
OBJECTS += ./mbed-os/rtos/RtosTimer.o
OBJECTS += ./mbed-os/rtos/Semaphore.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/SysTimer.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/TARGET_CORTEX_M/TOOLCHAIN_GCC/except.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/TARGET_CORTEX_M/mbed_rtx_fault_handler.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/mbed_boot.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/mbed_rtx_handlers.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/mbed_rtx_idle.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx4/cmsis_os1.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Config/RTX_Config.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_RTOS_M4_M7/irq_cm4f.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rt_OsEventObserver.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_delay.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_evflags.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_evr.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_kernel.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_lib.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_memory.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_mempool.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_msgqueue.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_mutex.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_semaphore.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_system.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_thread.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_timer.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/Source/os_systick.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/Source/os_tick_ptim.o
OBJECTS += ./mbed-os/rtos/Thread.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/device/TOOLCHAIN_GCC_ARM/startup_NRF52832.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/device/cmsis_nvic.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/device/system_nrf52.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/driver_nrf/pwm/nrf_drv_pwm.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/driver_nrf/saadc/nrf_drv_saadc.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_NRF52_COMMON/analogin_api.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_NRF52_COMMON/pwmout_api.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_advertising/ble_advertising.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_db_discovery/ble_db_discovery.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_debug_assert_handler/ble_debug_assert_handler.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_dtm/ble_dtm.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_racp/ble_racp.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_radio_notification/ble_radio_notification.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_services/ble_dfu/ble_dfu.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/common/ble_advdata.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/common/ble_conn_state.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/common/ble_srv_common.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/device_manager/device_manager_peripheral.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/gatt_cache_manager.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/gattc_cache_manager.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/gatts_cache_manager.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/id_manager.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/peer_data.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/peer_data_storage.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/peer_database.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/peer_id.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/peer_manager.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/pm_buffer.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/pm_mutex.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/security_dispatcher.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/security_manager.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/ble_flash/ble_flash.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/clock/nrf_drv_clock.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/common/nrf_drv_common.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/delay/nrf_delay.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/gpiote/nrf_drv_gpiote.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/hal/nrf_adc.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/hal/nrf_ecb.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/hal/nrf_nvmc.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/hal/nrf_saadc.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/ppi/nrf_drv_ppi.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/pstorage/pstorage.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/rng/nrf_drv_rng.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/spi_master/nrf_drv_spi.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/spi_slave/nrf_drv_spis.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/timer/nrf_drv_timer.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/bootloader_dfu/bootloader_util.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/bootloader_dfu/dfu_app_handler.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/bootloader_dfu/dfu_init_template.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/crc16/crc16.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/fds/fds.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/fstorage/fstorage.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/fstorage/fstorage_nosd.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/hci/hci_mem_pool.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/pwm/app_pwm.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/scheduler/app_scheduler.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/trace/app_trace.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/util/app_error.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/util/app_error_weak.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/util/app_util_platform.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/util/nrf_assert.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/util/nrf_log.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/util/sdk_mapped_flags.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/softdevice/common/softdevice_handler/softdevice_handler.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/softdevice/common/softdevice_handler/softdevice_handler_appsh.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/flash_api.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/gpio_api.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/i2c_api.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/itm_api.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/lp_ticker.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/nordic_critical.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/pinmap.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/port_api.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/reloc_vector_table.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/rtc_api.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/serial_api.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/sleep.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/spi_api.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/trng_api.o
OBJECTS += ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/us_ticker.o


INCLUDE_PATHS += -I../
INCLUDE_PATHS += -I../.
INCLUDE_PATHS += -I.././aconno_SEGGER_RTT
INCLUDE_PATHS += -I.././aconno_bsp
INCLUDE_PATHS += -I.././aconno_nrf52_uart
INCLUDE_PATHS += -I.././aconno_nrf52_uart/adc52832_common
INCLUDE_PATHS += -I.././mbed-os
INCLUDE_PATHS += -I.././mbed-os/cmsis
INCLUDE_PATHS += -I.././mbed-os/cmsis/TARGET_CORTEX_M
INCLUDE_PATHS += -I.././mbed-os/drivers
INCLUDE_PATHS += -I.././mbed-os/events
INCLUDE_PATHS += -I.././mbed-os/events/equeue
INCLUDE_PATHS += -I.././mbed-os/features
INCLUDE_PATHS += -I.././mbed-os/features/FEATURE_BLE
INCLUDE_PATHS += -I.././mbed-os/features/FEATURE_BLE/ble
INCLUDE_PATHS += -I.././mbed-os/features/FEATURE_BLE/ble/generic
INCLUDE_PATHS += -I.././mbed-os/features/FEATURE_BLE/ble/pal
INCLUDE_PATHS += -I.././mbed-os/features/FEATURE_BLE/ble/services
INCLUDE_PATHS += -I.././mbed-os/features/FEATURE_BLE/source
INCLUDE_PATHS += -I.././mbed-os/features/FEATURE_BLE/source/generic
INCLUDE_PATHS += -I.././mbed-os/features/FEATURE_BLE/source/services
INCLUDE_PATHS += -I.././mbed-os/features/FEATURE_BLE/targets
INCLUDE_PATHS += -I.././mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC
INCLUDE_PATHS += -I.././mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5
INCLUDE_PATHS += -I.././mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source
INCLUDE_PATHS += -I.././mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle
INCLUDE_PATHS += -I.././mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/custom
INCLUDE_PATHS += -I.././mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/common
INCLUDE_PATHS += -I.././mbed-os/features/cellular
INCLUDE_PATHS += -I.././mbed-os/features/cellular/easy_cellular
INCLUDE_PATHS += -I.././mbed-os/features/cellular/framework
INCLUDE_PATHS += -I.././mbed-os/features/cellular/framework/API
INCLUDE_PATHS += -I.././mbed-os/features/cellular/framework/AT
INCLUDE_PATHS += -I.././mbed-os/features/cellular/framework/common
INCLUDE_PATHS += -I.././mbed-os/features/cellular/framework/targets
INCLUDE_PATHS += -I.././mbed-os/features/cellular/framework/targets/QUECTEL
INCLUDE_PATHS += -I.././mbed-os/features/cellular/framework/targets/QUECTEL/BC95
INCLUDE_PATHS += -I.././mbed-os/features/cellular/framework/targets/QUECTEL/BG96
INCLUDE_PATHS += -I.././mbed-os/features/cellular/framework/targets/TELIT
INCLUDE_PATHS += -I.././mbed-os/features/cellular/framework/targets/TELIT/HE910
INCLUDE_PATHS += -I.././mbed-os/features/cellular/framework/targets/UBLOX
INCLUDE_PATHS += -I.././mbed-os/features/cellular/framework/targets/UBLOX/LISA_U
INCLUDE_PATHS += -I.././mbed-os/features/filesystem
INCLUDE_PATHS += -I.././mbed-os/features/filesystem/bd
INCLUDE_PATHS += -I.././mbed-os/features/filesystem/fat
INCLUDE_PATHS += -I.././mbed-os/features/filesystem/fat/ChaN
INCLUDE_PATHS += -I.././mbed-os/features/filesystem/littlefs
INCLUDE_PATHS += -I.././mbed-os/features/filesystem/littlefs/littlefs
INCLUDE_PATHS += -I.././mbed-os/features/frameworks
INCLUDE_PATHS += -I.././mbed-os/features/frameworks/greentea-client
INCLUDE_PATHS += -I.././mbed-os/features/frameworks/greentea-client/greentea-client
INCLUDE_PATHS += -I.././mbed-os/features/frameworks/greentea-client/source
INCLUDE_PATHS += -I.././mbed-os/features/frameworks/unity
INCLUDE_PATHS += -I.././mbed-os/features/frameworks/unity/source
INCLUDE_PATHS += -I.././mbed-os/features/frameworks/unity/unity
INCLUDE_PATHS += -I.././mbed-os/features/frameworks/utest
INCLUDE_PATHS += -I.././mbed-os/features/frameworks/utest/source
INCLUDE_PATHS += -I.././mbed-os/features/frameworks/utest/utest
INCLUDE_PATHS += -I.././mbed-os/features/lorawan
INCLUDE_PATHS += -I.././mbed-os/features/lorawan/lorastack
INCLUDE_PATHS += -I.././mbed-os/features/lorawan/lorastack/mac
INCLUDE_PATHS += -I.././mbed-os/features/lorawan/lorastack/phy
INCLUDE_PATHS += -I.././mbed-os/features/lorawan/system
INCLUDE_PATHS += -I.././mbed-os/features/mbedtls
INCLUDE_PATHS += -I.././mbed-os/features/mbedtls/importer
INCLUDE_PATHS += -I.././mbed-os/features/mbedtls/inc
INCLUDE_PATHS += -I.././mbed-os/features/mbedtls/inc/mbedtls
INCLUDE_PATHS += -I.././mbed-os/features/mbedtls/platform
INCLUDE_PATHS += -I.././mbed-os/features/mbedtls/platform/inc
INCLUDE_PATHS += -I.././mbed-os/features/mbedtls/platform/src
INCLUDE_PATHS += -I.././mbed-os/features/mbedtls/src
INCLUDE_PATHS += -I.././mbed-os/features/mbedtls/targets
INCLUDE_PATHS += -I.././mbed-os/features/nanostack
INCLUDE_PATHS += -I.././mbed-os/features/netsocket
INCLUDE_PATHS += -I.././mbed-os/features/netsocket/cellular
INCLUDE_PATHS += -I.././mbed-os/features/netsocket/cellular/generic_modem_driver
INCLUDE_PATHS += -I.././mbed-os/features/nvstore
INCLUDE_PATHS += -I.././mbed-os/features/nvstore/source
INCLUDE_PATHS += -I.././mbed-os/features/storage
INCLUDE_PATHS += -I.././mbed-os/hal
INCLUDE_PATHS += -I.././mbed-os/hal/storage_abstraction
INCLUDE_PATHS += -I.././mbed-os/platform
INCLUDE_PATHS += -I.././mbed-os/rtos
INCLUDE_PATHS += -I.././mbed-os/rtos/TARGET_CORTEX
INCLUDE_PATHS += -I.././mbed-os/rtos/TARGET_CORTEX/TARGET_CORTEX_M
INCLUDE_PATHS += -I.././mbed-os/rtos/TARGET_CORTEX/TARGET_CORTEX_M/TOOLCHAIN_GCC
INCLUDE_PATHS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx4
INCLUDE_PATHS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5
INCLUDE_PATHS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/Include
INCLUDE_PATHS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX
INCLUDE_PATHS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Config
INCLUDE_PATHS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Include
INCLUDE_PATHS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source
INCLUDE_PATHS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC
INCLUDE_PATHS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_RTOS_M4_M7
INCLUDE_PATHS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/Source
INCLUDE_PATHS += -I.././mbed-os/targets
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TARGET_NRF52_DK
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/device
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/device/TOOLCHAIN_GCC_ARM
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/driver_nrf
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/driver_nrf/pwm
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/driver_nrf/saadc
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/softdevice
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/softdevice/s132
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/softdevice/s132/headers
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/softdevice/s132/headers/nrf52
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/softdevice/s132/hex
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk_patch
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_NRF52_COMMON
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_advertising
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_db_discovery
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_debug_assert_handler
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_dtm
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_error_log
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_racp
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_radio_notification
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_services
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_services/ble_dfu
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/common
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/device_manager
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/device_manager/config
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/device
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/ble_flash
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/clock
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/common
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/config
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/delay
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/gpiote
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/hal
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/ppi
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/pstorage
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/pstorage/config
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/rng
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/spi_master
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/spi_slave
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/timer
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/bootloader_dfu
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/bootloader_dfu/hci_transport
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/crc16
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/experimental_section_vars
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/fds
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/fds/config
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/fstorage
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/fstorage/config
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/hci
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/hci/config
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/pwm
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/scheduler
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/trace
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/util
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/softdevice
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/softdevice/common
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/softdevice/common/softdevice_handler
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/porting_tools

LIBRARY_PATHS :=
LIBRARIES :=
LINKER_SCRIPT ?= .././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/device/TOOLCHAIN_GCC_ARM/NRF52832.ld

# Objects and Paths
###############################################################################
# Tools and Flags

AS      = 'arm-none-eabi-gcc' '-x' 'assembler-with-cpp' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-O0' '-g3' '-DMBED_DEBUG' '-DMBED_TRAP_ERRORS_ENABLED=1' '-mcpu=cortex-m4' '-mthumb' '-mfpu=fpv4-sp-d16' '-mfloat-abi=softfp'
CC      = 'arm-none-eabi-gcc' '-std=gnu99' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-O0' '-g3' '-DMBED_DEBUG' '-DMBED_TRAP_ERRORS_ENABLED=1' '-mcpu=cortex-m4' '-mthumb' '-mfpu=fpv4-sp-d16' '-mfloat-abi=softfp'
CPP     = 'arm-none-eabi-g++' '-std=gnu++98' '-fno-rtti' '-Wvla' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-O0' '-g3' '-DMBED_DEBUG' '-DMBED_TRAP_ERRORS_ENABLED=1' '-mcpu=cortex-m4' '-mthumb' '-mfpu=fpv4-sp-d16' '-mfloat-abi=softfp'
LD      = 'arm-none-eabi-gcc'
ELF2BIN = 'arm-none-eabi-objcopy'
PREPROC = 'arm-none-eabi-cpp' '-E' '-P' '-Wl,--gc-sections' '-Wl,--wrap,main' '-Wl,--wrap,_malloc_r' '-Wl,--wrap,_free_r' '-Wl,--wrap,_realloc_r' '-Wl,--wrap,_memalign_r' '-Wl,--wrap,_calloc_r' '-Wl,--wrap,exit' '-Wl,--wrap,atexit' '-Wl,-n' '-mcpu=cortex-m4' '-mthumb' '-mfpu=fpv4-sp-d16' '-mfloat-abi=softfp'

SREC_CAT = srec_cat

C_FLAGS += -std=gnu99
C_FLAGS += -DTARGET_MCU_NRF52832
C_FLAGS += -DDEVICE_LOWPOWERTIMER=1
C_FLAGS += -DTARGET_SDK11
C_FLAGS += -D__MBED__=1
C_FLAGS += -DNRF52_PAN_53
C_FLAGS += -DTARGET_NRF52_COMMON
C_FLAGS += -DDEVICE_PORTINOUT=1
C_FLAGS += -DTARGET_RTOS_M4_M7
C_FLAGS += -DMBED_BUILD_TIMESTAMP=1578231544.86
C_FLAGS += -DDEVICE_RTC=1
C_FLAGS += -DTOOLCHAIN_object
C_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
C_FLAGS += -D__CMSIS_RTOS
C_FLAGS += -DBOARD_PCA10040
C_FLAGS += -DDEVICE_ITM=1
C_FLAGS += -DDEVICE_SPISLAVE=1
C_FLAGS += -DNRF52_PAN_12
C_FLAGS += -DTOOLCHAIN_GCC
C_FLAGS += -DNRF52_PAN_58
C_FLAGS += -DDEVICE_I2C_ASYNCH=1
C_FLAGS += -DNRF52_PAN_55
C_FLAGS += -DNRF52_PAN_54
C_FLAGS += -DTARGET_CORTEX_M
C_FLAGS += -DTARGET_DEBUG
C_FLAGS += -DTARGET_NRF52_DK
C_FLAGS += -DNRF52_PAN_36
C_FLAGS += -DTARGET_LIKE_CORTEX_M4
C_FLAGS += -DTARGET_M4
C_FLAGS += -DTARGET_UVISOR_UNSUPPORTED
C_FLAGS += -DTARGET_NRF5
C_FLAGS += -DFEATURE_BLE=1
C_FLAGS += -DTARGET_MCU_NRF52
C_FLAGS += -DCMSIS_VECTAB_VIRTUAL
C_FLAGS += -DDEVICE_SERIAL=1
C_FLAGS += -DDEVICE_SPI_ASYNCH=1
C_FLAGS += -DMBED_TICKLESS
C_FLAGS += -DNRF52
C_FLAGS += -DTARGET_CORTEX
C_FLAGS += -DDEVICE_I2C=1
C_FLAGS += -DDEVICE_PORTOUT=1
C_FLAGS += -DTARGET_NRF52832
C_FLAGS += -D__CORTEX_M4
C_FLAGS += -DTARGET_FF_ARDUINO
C_FLAGS += -D__FPU_PRESENT=1
C_FLAGS += -DS132
C_FLAGS += -DDEVICE_SLEEP=1
C_FLAGS += -DDEVICE_PORTIN=1
C_FLAGS += -DNRF52_PAN_51
C_FLAGS += -DDEVICE_STCLK_OFF_DURING_SLEEP=1
C_FLAGS += -DTARGET_NORDIC
C_FLAGS += -DNRF52_PAN_30
C_FLAGS += -DBLE_STACK_SUPPORT_REQD
C_FLAGS += -DNRF52_PAN_15
C_FLAGS += -DCONFIG_GPIO_AS_PINRESET
C_FLAGS += -DDEVICE_TRNG=1
C_FLAGS += -DTARGET_LIKE_MBED
C_FLAGS += -D__MBED_CMSIS_RTOS_CM
C_FLAGS += -DNRF52_PAN_31
C_FLAGS += -DTOOLCHAIN_GCC_ARM
C_FLAGS += -DSWI_DISABLE0
C_FLAGS += -DSOFTDEVICE_PRESENT
C_FLAGS += -DDEVICE_SPI=1
C_FLAGS += -DCMSIS_VECTAB_VIRTUAL_HEADER_FILE=\"cmsis_nvic.h\"
C_FLAGS += -DDEVICE_INTERRUPTIN=1
C_FLAGS += -DNRF52_PAN_64
C_FLAGS += -DNRF52_PAN_20
C_FLAGS += -DDEVICE_ANALOGIN=1
C_FLAGS += -DDEVICE_PWMOUT=1
C_FLAGS += -DNRF52_PAN_62
C_FLAGS += -DNRF52_PAN_63
C_FLAGS += -DDEVICE_FLASH=1
C_FLAGS += -DARM_MATH_CM4
C_FLAGS += -DDEVICE_SERIAL_FC=1
C_FLAGS += -include
C_FLAGS += mbed_config.h

CXX_FLAGS += -std=gnu++98
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -DTARGET_MCU_NRF52832
CXX_FLAGS += -DDEVICE_LOWPOWERTIMER=1
CXX_FLAGS += -DTARGET_SDK11
CXX_FLAGS += -D__MBED__=1
CXX_FLAGS += -DNRF52_PAN_53
CXX_FLAGS += -DTARGET_NRF52_COMMON
CXX_FLAGS += -DDEVICE_PORTINOUT=1
CXX_FLAGS += -DTARGET_RTOS_M4_M7
CXX_FLAGS += -DMBED_BUILD_TIMESTAMP=1578231544.86
CXX_FLAGS += -DDEVICE_RTC=1
CXX_FLAGS += -DTOOLCHAIN_object
CXX_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
CXX_FLAGS += -D__CMSIS_RTOS
CXX_FLAGS += -DBOARD_PCA10040
CXX_FLAGS += -DDEVICE_ITM=1
CXX_FLAGS += -DDEVICE_SPISLAVE=1
CXX_FLAGS += -DNRF52_PAN_12
CXX_FLAGS += -DTOOLCHAIN_GCC
CXX_FLAGS += -DNRF52_PAN_58
CXX_FLAGS += -DDEVICE_I2C_ASYNCH=1
CXX_FLAGS += -DNRF52_PAN_55
CXX_FLAGS += -DNRF52_PAN_54
CXX_FLAGS += -DTARGET_CORTEX_M
CXX_FLAGS += -DTARGET_DEBUG
CXX_FLAGS += -DTARGET_NRF52_DK
CXX_FLAGS += -DNRF52_PAN_36
CXX_FLAGS += -DTARGET_LIKE_CORTEX_M4
CXX_FLAGS += -DTARGET_M4
CXX_FLAGS += -DTARGET_UVISOR_UNSUPPORTED
CXX_FLAGS += -DTARGET_NRF5
CXX_FLAGS += -DFEATURE_BLE=1
CXX_FLAGS += -DTARGET_MCU_NRF52
CXX_FLAGS += -DCMSIS_VECTAB_VIRTUAL
CXX_FLAGS += -DDEVICE_SERIAL=1
CXX_FLAGS += -DDEVICE_SPI_ASYNCH=1
CXX_FLAGS += -DMBED_TICKLESS
CXX_FLAGS += -DNRF52
CXX_FLAGS += -DTARGET_CORTEX
CXX_FLAGS += -DDEVICE_I2C=1
CXX_FLAGS += -DDEVICE_PORTOUT=1
CXX_FLAGS += -DTARGET_NRF52832
CXX_FLAGS += -D__CORTEX_M4
CXX_FLAGS += -DTARGET_FF_ARDUINO
CXX_FLAGS += -D__FPU_PRESENT=1
CXX_FLAGS += -DS132
CXX_FLAGS += -DDEVICE_SLEEP=1
CXX_FLAGS += -DDEVICE_PORTIN=1
CXX_FLAGS += -DNRF52_PAN_51
CXX_FLAGS += -DDEVICE_STCLK_OFF_DURING_SLEEP=1
CXX_FLAGS += -DTARGET_NORDIC
CXX_FLAGS += -DNRF52_PAN_30
CXX_FLAGS += -DBLE_STACK_SUPPORT_REQD
CXX_FLAGS += -DNRF52_PAN_15
CXX_FLAGS += -DCONFIG_GPIO_AS_PINRESET
CXX_FLAGS += -DDEVICE_TRNG=1
CXX_FLAGS += -DTARGET_LIKE_MBED
CXX_FLAGS += -D__MBED_CMSIS_RTOS_CM
CXX_FLAGS += -DNRF52_PAN_31
CXX_FLAGS += -DTOOLCHAIN_GCC_ARM
CXX_FLAGS += -DSWI_DISABLE0
CXX_FLAGS += -DSOFTDEVICE_PRESENT
CXX_FLAGS += -DDEVICE_SPI=1
CXX_FLAGS += -DCMSIS_VECTAB_VIRTUAL_HEADER_FILE=\"cmsis_nvic.h\"
CXX_FLAGS += -DDEVICE_INTERRUPTIN=1
CXX_FLAGS += -DNRF52_PAN_64
CXX_FLAGS += -DNRF52_PAN_20
CXX_FLAGS += -DDEVICE_ANALOGIN=1
CXX_FLAGS += -DDEVICE_PWMOUT=1
CXX_FLAGS += -DNRF52_PAN_62
CXX_FLAGS += -DNRF52_PAN_63
CXX_FLAGS += -DDEVICE_FLASH=1
CXX_FLAGS += -DARM_MATH_CM4
CXX_FLAGS += -DDEVICE_SERIAL_FC=1
CXX_FLAGS += -include
CXX_FLAGS += mbed_config.h

ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -DCMSIS_VECTAB_VIRTUAL
ASM_FLAGS += -DNRF52
ASM_FLAGS += -D__FPU_PRESENT=1
ASM_FLAGS += -D__MBED_CMSIS_RTOS_CM
ASM_FLAGS += -D__CMSIS_RTOS
ASM_FLAGS += -DBOARD_PCA10040
ASM_FLAGS += -DNRF52_PAN_12
ASM_FLAGS += -DNRF52_PAN_15
ASM_FLAGS += -DNRF52_PAN_58
ASM_FLAGS += -DNRF52_PAN_55
ASM_FLAGS += -DNRF52_PAN_54
ASM_FLAGS += -DNRF52_PAN_31
ASM_FLAGS += -DNRF52_PAN_30
ASM_FLAGS += -DNRF52_PAN_51
ASM_FLAGS += -DNRF52_PAN_36
ASM_FLAGS += -DNRF52_PAN_53
ASM_FLAGS += -DMBED_TICKLESS
ASM_FLAGS += -DTARGET_NRF52832
ASM_FLAGS += -D__CORTEX_M4
ASM_FLAGS += -DS132
ASM_FLAGS += -DCONFIG_GPIO_AS_PINRESET
ASM_FLAGS += -DBLE_STACK_SUPPORT_REQD
ASM_FLAGS += -DSWI_DISABLE0
ASM_FLAGS += -DSOFTDEVICE_PRESENT
ASM_FLAGS += -DCMSIS_VECTAB_VIRTUAL_HEADER_FILE=\"cmsis_nvic.h\"
ASM_FLAGS += -DNRF52_PAN_64
ASM_FLAGS += -DNRF52_PAN_20
ASM_FLAGS += -DNRF52_PAN_62
ASM_FLAGS += -DNRF52_PAN_63
ASM_FLAGS += -DARM_MATH_CM4
ASM_FLAGS += -I../.
ASM_FLAGS += -I.././aconno_bsp
ASM_FLAGS += -I.././aconno_nrf52_uart
ASM_FLAGS += -I.././aconno_nrf52_uart/adc52832_common
ASM_FLAGS += -I.././aconno_SEGGER_RTT
ASM_FLAGS += -I.././mbed-os
ASM_FLAGS += -I.././mbed-os/cmsis
ASM_FLAGS += -I.././mbed-os/cmsis/TARGET_CORTEX_M
ASM_FLAGS += -I.././mbed-os/drivers
ASM_FLAGS += -I.././mbed-os/events
ASM_FLAGS += -I.././mbed-os/events/equeue
ASM_FLAGS += -I.././mbed-os/features
ASM_FLAGS += -I.././mbed-os/features/cellular
ASM_FLAGS += -I.././mbed-os/features/cellular/easy_cellular
ASM_FLAGS += -I.././mbed-os/features/cellular/framework
ASM_FLAGS += -I.././mbed-os/features/cellular/framework/API
ASM_FLAGS += -I.././mbed-os/features/cellular/framework/AT
ASM_FLAGS += -I.././mbed-os/features/cellular/framework/common
ASM_FLAGS += -I.././mbed-os/features/cellular/framework/targets
ASM_FLAGS += -I.././mbed-os/features/cellular/framework/targets/QUECTEL
ASM_FLAGS += -I.././mbed-os/features/cellular/framework/targets/QUECTEL/BC95
ASM_FLAGS += -I.././mbed-os/features/cellular/framework/targets/QUECTEL/BG96
ASM_FLAGS += -I.././mbed-os/features/cellular/framework/targets/TELIT
ASM_FLAGS += -I.././mbed-os/features/cellular/framework/targets/TELIT/HE910
ASM_FLAGS += -I.././mbed-os/features/cellular/framework/targets/UBLOX
ASM_FLAGS += -I.././mbed-os/features/cellular/framework/targets/UBLOX/LISA_U
ASM_FLAGS += -I.././mbed-os/features/filesystem
ASM_FLAGS += -I.././mbed-os/features/filesystem/bd
ASM_FLAGS += -I.././mbed-os/features/filesystem/fat
ASM_FLAGS += -I.././mbed-os/features/filesystem/fat/ChaN
ASM_FLAGS += -I.././mbed-os/features/filesystem/littlefs
ASM_FLAGS += -I.././mbed-os/features/filesystem/littlefs/littlefs
ASM_FLAGS += -I.././mbed-os/features/frameworks
ASM_FLAGS += -I.././mbed-os/features/frameworks/greentea-client
ASM_FLAGS += -I.././mbed-os/features/frameworks/greentea-client/greentea-client
ASM_FLAGS += -I.././mbed-os/features/frameworks/greentea-client/source
ASM_FLAGS += -I.././mbed-os/features/frameworks/unity
ASM_FLAGS += -I.././mbed-os/features/frameworks/unity/source
ASM_FLAGS += -I.././mbed-os/features/frameworks/unity/unity
ASM_FLAGS += -I.././mbed-os/features/frameworks/utest
ASM_FLAGS += -I.././mbed-os/features/frameworks/utest/source
ASM_FLAGS += -I.././mbed-os/features/frameworks/utest/utest
ASM_FLAGS += -I.././mbed-os/features/lorawan
ASM_FLAGS += -I.././mbed-os/features/lorawan/lorastack
ASM_FLAGS += -I.././mbed-os/features/lorawan/lorastack/mac
ASM_FLAGS += -I.././mbed-os/features/lorawan/lorastack/phy
ASM_FLAGS += -I.././mbed-os/features/lorawan/system
ASM_FLAGS += -I.././mbed-os/features/mbedtls
ASM_FLAGS += -I.././mbed-os/features/mbedtls/importer
ASM_FLAGS += -I.././mbed-os/features/mbedtls/inc
ASM_FLAGS += -I.././mbed-os/features/mbedtls/inc/mbedtls
ASM_FLAGS += -I.././mbed-os/features/mbedtls/platform
ASM_FLAGS += -I.././mbed-os/features/mbedtls/platform/inc
ASM_FLAGS += -I.././mbed-os/features/mbedtls/platform/src
ASM_FLAGS += -I.././mbed-os/features/mbedtls/src
ASM_FLAGS += -I.././mbed-os/features/mbedtls/targets
ASM_FLAGS += -I.././mbed-os/features/nanostack
ASM_FLAGS += -I.././mbed-os/features/netsocket
ASM_FLAGS += -I.././mbed-os/features/netsocket/cellular
ASM_FLAGS += -I.././mbed-os/features/netsocket/cellular/generic_modem_driver
ASM_FLAGS += -I.././mbed-os/features/nvstore
ASM_FLAGS += -I.././mbed-os/features/nvstore/source
ASM_FLAGS += -I.././mbed-os/features/storage
ASM_FLAGS += -I.././mbed-os/hal
ASM_FLAGS += -I.././mbed-os/hal/storage_abstraction
ASM_FLAGS += -I.././mbed-os/platform
ASM_FLAGS += -I.././mbed-os/rtos
ASM_FLAGS += -I.././mbed-os/rtos/TARGET_CORTEX
ASM_FLAGS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx4
ASM_FLAGS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5
ASM_FLAGS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/Include
ASM_FLAGS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX
ASM_FLAGS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Config
ASM_FLAGS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Include
ASM_FLAGS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source
ASM_FLAGS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC
ASM_FLAGS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_RTOS_M4_M7
ASM_FLAGS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/Source
ASM_FLAGS += -I.././mbed-os/rtos/TARGET_CORTEX/TARGET_CORTEX_M
ASM_FLAGS += -I.././mbed-os/rtos/TARGET_CORTEX/TARGET_CORTEX_M/TOOLCHAIN_GCC
ASM_FLAGS += -I.././mbed-os/targets
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/porting_tools
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/device
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/device/TOOLCHAIN_GCC_ARM
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/driver_nrf
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/driver_nrf/pwm
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/driver_nrf/saadc
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/softdevice
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/softdevice/s132
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/softdevice/s132/headers
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/softdevice/s132/headers/nrf52
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/softdevice/s132/hex
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk_patch
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TARGET_NRF52_DK
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_NRF52_COMMON
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_advertising
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_db_discovery
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_debug_assert_handler
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_dtm
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_error_log
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_racp
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_radio_notification
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_services
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_services/ble_dfu
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/common
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/device_manager
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/device_manager/config
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/device
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/ble_flash
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/clock
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/common
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/config
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/delay
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/gpiote
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/hal
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/ppi
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/pstorage
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/pstorage/config
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/rng
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/spi_master
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/spi_slave
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/timer
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/bootloader_dfu
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/bootloader_dfu/hci_transport
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/crc16
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/experimental_section_vars
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/fds
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/fds/config
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/fstorage
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/fstorage/config
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/hci
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/hci/config
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/pwm
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/scheduler
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/trace
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/util
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/softdevice
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/softdevice/common
ASM_FLAGS += -I.././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/softdevice/common/softdevice_handler
ASM_FLAGS += -I.././mbed-os/features/FEATURE_BLE
ASM_FLAGS += -I.././mbed-os/features/FEATURE_BLE/ble
ASM_FLAGS += -I.././mbed-os/features/FEATURE_BLE/ble/generic
ASM_FLAGS += -I.././mbed-os/features/FEATURE_BLE/ble/pal
ASM_FLAGS += -I.././mbed-os/features/FEATURE_BLE/ble/services
ASM_FLAGS += -I.././mbed-os/features/FEATURE_BLE/source
ASM_FLAGS += -I.././mbed-os/features/FEATURE_BLE/source/generic
ASM_FLAGS += -I.././mbed-os/features/FEATURE_BLE/source/services
ASM_FLAGS += -I.././mbed-os/features/FEATURE_BLE/targets
ASM_FLAGS += -I.././mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC
ASM_FLAGS += -I.././mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5
ASM_FLAGS += -I.././mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source
ASM_FLAGS += -I.././mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle
ASM_FLAGS += -I.././mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/custom
ASM_FLAGS += -I.././mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/common


LD_FLAGS :=-Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,_malloc_r -Wl,--wrap,_free_r -Wl,--wrap,_realloc_r -Wl,--wrap,_memalign_r -Wl,--wrap,_calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=softfp 
LD_SYS_LIBS :=-Wl,--start-group -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys  -Wl,--end-group

# Tools and Flags
###############################################################################
# Rules

.PHONY: all lst size

all: $(PROJECT).bin $(PROJECT)-combined.hex size


.s.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  


.S.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  

.c.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CC) $(C_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.cpp.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CPP) $(CXX_FLAGS) $(INCLUDE_PATHS) -o $@ $<


$(PROJECT).link_script.ld: $(LINKER_SCRIPT)
	@$(PREPROC) $< -o $@



$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS) $(PROJECT).link_script.ld 
	+@echo "link: $(notdir $@)"
	@$(LD) $(LD_FLAGS) -T $(filter-out %.o, $^) $(LIBRARY_PATHS) --output $@ $(filter %.o, $^) $(LIBRARIES) $(LD_SYS_LIBS)


$(PROJECT).bin: $(PROJECT).elf
	$(ELF2BIN) -O binary $< $@


$(PROJECT).hex: $(PROJECT).elf
	$(ELF2BIN) -O ihex $< $@


$(PROJECT)-combined.hex: $(PROJECT).hex
	+@echo "NOTE: the $(SREC_CAT) binary is required to be present in your PATH. Please see http://srecord.sourceforge.net/ for more information."
	$(SREC_CAT) .././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/softdevice/s132/hex/s132_nrf52_2.0.0_softdevice.hex  -intel $(PROJECT).hex -intel -o $(PROJECT)-combined.hex -intel --line-length=44
	+@echo "===== hex file ready to flash: $(OBJDIR)/$@ ====="

# Rules
###############################################################################
# Dependencies

DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d)
-include $(DEPS)
endif

# Dependencies
###############################################################################
